def Menu_Principal(): 
    print ("")
    print("╔════════════════════════════════════╗".center(120))
    print("║            MENÚ PRINCIPAL          ║".center(120))
    print("╠════════════════════════════════════╣".center(120))
    print("║ 1. Gestion de juegos               ║".center(120))
    print("║ 2. Consultas y valoraciones        ║".center(120))
    print("║ 3. Salir del sistema               ║".center(120))
    print("╚════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ".rjust(20)))
    print ("")
    print ("===================================== ".rjust(20))
    print ("")
    return opc 

def Menu_Gestion_Juegos(): 
    print ("")
    print("╔════════════════════════════════════╗".center(120))
    print("║         GESTION DE JUEGOS          ║".center(120))
    print("╠════════════════════════════════════╣".center(120))
    print("║ 1. Registrar juego                 ║".center(120))
    print("║ 2. Modificar juego                 ║".center(120))
    print("║ 3. Eliminar juego                  ║".center(120))
    print("║ 4. Volver                          ║".center(120))
    print("╚════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ".rjust(20)))
    print ("")
    print ("===================================== ".rjust(20))
    print ("")
    return opc  

def Menu_Consultas_Valoracione():
    print ("")
    print("╔════════════════════════════════════╗".center(120))
    print("║       CONSULTAS Y VALORACIONES     ║".center(120))
    print("╠════════════════════════════════════╣".center(120))
    print("║ 1. Consultar juego                 ║".center(120))
    print("║ 2. Valorar juego                   ║".center(120))
    print("║ 3. Top valoraciones                ║".center(120))
    print("║ 4. Volver                          ║".center(120))
    print("╚════════════════════════════════════╝".center(120))
    print ("")
    print ("=====================================".rjust(20))
    opc = int(input("\n Ingrese la opcion que desea usar : ".rjust(20)))
    print ("")
    print ("===================================== ".rjust(20))
    print ("")
    return opc 